name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: rumcake-firmware
    steps:
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly-2023-12-05
        target: thumbv7em-none-eabihf
        components: rust-src, rustfmt, llvm-tools-preview
    - name: Install cargo-objcopy
      run: cargo install cargo-binutils

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build project
      run: sh build.sh

    - name: Zip artifacts
      run: |
        export PROJECT_NAME=$(awk -F '"' '/^name = "/ {print $2 ; exit}' Cargo.toml)
        echo "PROJECT_NAME=$PROJECT_NAME" >> "$GITHUB_ENV"
        mkdir dist
        cp left.bin dist/left.bin
        cp right.bin dist/right.bin
        zip -r "$PROJECT_NAME".zip dist/

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.PROJECT_NAME }}
        path: ${{ env.PROJECT_NAME }}.zip
